"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-06 17:57:31.635947
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_user",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("platform_role", sa.String(length=32), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_user")),
        sa.UniqueConstraint("email", name=op.f("uq_app_user_email")),
    )
    op.create_table(
        "doc_type_def",
        sa.Column("code", sa.String(length=8), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("parent_type", sa.String(length=8), nullable=True),
        sa.Column("sort", sa.Integer(), nullable=False),
        sa.Column("sections", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_doc_type_def")),
    )
    op.create_table(
        "standard_def",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("layer", sa.String(length=32), nullable=False),
        sa.Column("structure", sa.String(length=32), nullable=False),
        sa.Column("integration_mode", sa.String(length=32), nullable=False),
        sa.Column("scope_codes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_standard_def")),
    )
    op.create_table(
        "tenant",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenant")),
        sa.UniqueConstraint("slug", name=op.f("uq_tenant_slug")),
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=32), nullable=False),
        sa.Column("entity_id", sa.String(length=64), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("prev_hash", sa.String(length=64), nullable=False),
        sa.Column("hash", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["app_user.id"],
            name=op.f("fk_audit_log_actor_id_app_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_audit_log_tenant_id_tenant"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(op.f("ix_audit_log_tenant_id"), "audit_log", ["tenant_id"], unique=False)
    op.create_table(
        "auth_session",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_auth_session_user_id_app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_session")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_auth_session_token_hash")),
    )
    op.create_table(
        "doc_sequence",
        sa.Column("root_system_id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("last", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_doc_sequence_tenant_id_tenant"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("root_system_id", "key", name=op.f("pk_doc_sequence")),
    )
    op.create_index(op.f("ix_doc_sequence_tenant_id"), "doc_sequence", ["tenant_id"], unique=False)
    op.create_table(
        "login_token",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_login_token_user_id_app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_login_token")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_login_token_token_hash")),
    )
    op.create_table(
        "membership",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("tenant_role", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_membership_tenant_id_tenant"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_membership_user_id_app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "tenant_id", name=op.f("pk_membership")),
    )
    op.create_table(
        "org_unit",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("sort", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["org_unit.id"],
            name=op.f("fk_org_unit_parent_id_org_unit"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_org_unit_tenant_id_tenant"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_org_unit")),
    )
    op.create_index(op.f("ix_org_unit_tenant_id"), "org_unit", ["tenant_id"], unique=False)
    op.create_table(
        "scope_code",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=True),
        sa.Column("code", sa.String(length=8), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("layer", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_scope_code_tenant_id_tenant"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scope_code")),
    )
    op.create_index(
        "uq_scope_code_tenant_code",
        "scope_code",
        [
            sa.literal_column("coalesce(tenant_id, '00000000-0000-0000-0000-000000000000'::uuid)"),
            "code",
        ],
        unique=True,
    )
    op.create_table(
        "process_system",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("org_unit_id", sa.UUID(), nullable=False),
        sa.Column("parent_system_id", sa.UUID(), nullable=True),
        sa.Column("root_system_id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["app_user.id"],
            name=op.f("fk_process_system_created_by_app_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["org_unit_id"],
            ["org_unit.id"],
            name=op.f("fk_process_system_org_unit_id_org_unit"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["parent_system_id"],
            ["process_system.id"],
            name=op.f("fk_process_system_parent_system_id_process_system"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_process_system_tenant_id_tenant"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_process_system")),
        sa.UniqueConstraint("tenant_id", "slug", name=op.f("uq_process_system_tenant_id_slug")),
    )
    op.create_index(
        op.f("ix_process_system_tenant_id"), "process_system", ["tenant_id"], unique=False
    )
    op.create_table(
        "document",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("system_id", sa.UUID(), nullable=False),
        sa.Column("doc_type", sa.String(length=8), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("scope_code", sa.String(length=8), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["app_user.id"],
            name=op.f("fk_document_created_by_app_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["doc_type"], ["doc_type_def.code"], name=op.f("fk_document_doc_type_doc_type_def")
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["document.id"],
            name=op.f("fk_document_parent_id_document"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["system_id"],
            ["process_system.id"],
            name=op.f("fk_document_system_id_process_system"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_document_tenant_id_tenant"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document")),
        sa.UniqueConstraint("system_id", "code", name=op.f("uq_document_system_id_code")),
    )
    op.create_index(op.f("ix_document_parent_id"), "document", ["parent_id"], unique=False)
    op.create_index(op.f("ix_document_system_id"), "document", ["system_id"], unique=False)
    op.create_index(op.f("ix_document_tenant_id"), "document", ["tenant_id"], unique=False)
    op.create_table(
        "role_assignment",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("system_id", sa.UUID(), nullable=True),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["system_id"],
            ["process_system.id"],
            name=op.f("fk_role_assignment_system_id_process_system"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_role_assignment_tenant_id_tenant"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_role_assignment_user_id_app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role_assignment")),
    )
    op.create_index(
        op.f("ix_role_assignment_tenant_id"), "role_assignment", ["tenant_id"], unique=False
    )
    op.create_index(
        "uq_role_assignment_scope",
        "role_assignment",
        [
            "tenant_id",
            "user_id",
            "role",
            sa.literal_column("coalesce(system_id, '00000000-0000-0000-0000-000000000000'::uuid)"),
        ],
        unique=True,
    )
    op.create_table(
        "document_link",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("from_id", sa.UUID(), nullable=False),
        sa.Column("to_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["from_id"],
            ["document.id"],
            name=op.f("fk_document_link_from_id_document"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_document_link_tenant_id_tenant"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["to_id"],
            ["document.id"],
            name=op.f("fk_document_link_to_id_document"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_link")),
        sa.UniqueConstraint(
            "from_id", "to_id", "kind", name=op.f("uq_document_link_from_id_to_id_kind")
        ),
    )
    op.create_index(
        op.f("ix_document_link_tenant_id"), "document_link", ["tenant_id"], unique=False
    )
    op.create_table(
        "document_revision",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("sections", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("structured", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("change_kind", sa.String(length=8), nullable=False),
        sa.Column("change_summary", sa.Text(), nullable=False),
        sa.Column("based_on_revision_id", sa.UUID(), nullable=True),
        sa.Column("author_id", sa.UUID(), nullable=True),
        sa.Column("reviewer_id", sa.UUID(), nullable=True),
        sa.Column("review_comment", sa.Text(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("generated_by", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["app_user.id"],
            name=op.f("fk_document_revision_author_id_app_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["based_on_revision_id"],
            ["document_revision.id"],
            name=op.f("fk_document_revision_based_on_revision_id_document_revision"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.id"],
            name=op.f("fk_document_revision_document_id_document"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["app_user.id"],
            name=op.f("fk_document_revision_reviewer_id_app_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_document_revision_tenant_id_tenant"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_revision")),
    )
    op.create_index(
        op.f("ix_document_revision_document_id"), "document_revision", ["document_id"], unique=False
    )
    op.create_index(
        op.f("ix_document_revision_tenant_id"), "document_revision", ["tenant_id"], unique=False
    )
    op.create_index(
        "uq_document_revision_approved",
        "document_revision",
        ["document_id"],
        unique=True,
        postgresql_where=sa.text("status = 'approved'"),
    )
    op.create_index(
        "uq_document_revision_open",
        "document_revision",
        ["document_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('draft', 'in_review')"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_document_revision_open",
        table_name="document_revision",
        postgresql_where=sa.text("status IN ('draft', 'in_review')"),
    )
    op.drop_index(
        "uq_document_revision_approved",
        table_name="document_revision",
        postgresql_where=sa.text("status = 'approved'"),
    )
    op.drop_index(op.f("ix_document_revision_tenant_id"), table_name="document_revision")
    op.drop_index(op.f("ix_document_revision_document_id"), table_name="document_revision")
    op.drop_table("document_revision")
    op.drop_index(op.f("ix_document_link_tenant_id"), table_name="document_link")
    op.drop_table("document_link")
    op.drop_index("uq_role_assignment_scope", table_name="role_assignment")
    op.drop_index(op.f("ix_role_assignment_tenant_id"), table_name="role_assignment")
    op.drop_table("role_assignment")
    op.drop_index(op.f("ix_document_tenant_id"), table_name="document")
    op.drop_index(op.f("ix_document_system_id"), table_name="document")
    op.drop_index(op.f("ix_document_parent_id"), table_name="document")
    op.drop_table("document")
    op.drop_index(op.f("ix_process_system_tenant_id"), table_name="process_system")
    op.drop_table("process_system")
    op.drop_index("uq_scope_code_tenant_code", table_name="scope_code")
    op.drop_table("scope_code")
    op.drop_index(op.f("ix_org_unit_tenant_id"), table_name="org_unit")
    op.drop_table("org_unit")
    op.drop_table("membership")
    op.drop_table("login_token")
    op.drop_index(op.f("ix_doc_sequence_tenant_id"), table_name="doc_sequence")
    op.drop_table("doc_sequence")
    op.drop_table("auth_session")
    op.drop_index(op.f("ix_audit_log_tenant_id"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_table("tenant")
    op.drop_table("standard_def")
    op.drop_table("doc_type_def")
    op.drop_table("app_user")
    # ### end Alembic commands ###
