"""sources requirements runs

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-06 22:19:54.485582
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0004"
down_revision = "0003"
branch_labels = None
depends_on = None

APP_ROLE = "pm_app"
TENANT_TABLES = [
    "source_document",
    "source_page",
    "source_clause",
    "requirement",
    "run",
    "run_event",
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "source_document",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("edition", sa.String(length=100), nullable=False),
        sa.Column("filename", sa.String(length=300), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("storage_key", sa.String(length=300), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=False),
        sa.Column("sparse_pages", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("mining_state", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("uploaded_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("confirmed_by", sa.UUID(), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["confirmed_by"],
            ["app_user.id"],
            name=op.f("fk_source_document_confirmed_by_app_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_source_document_tenant_id_tenant"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["app_user.id"],
            name=op.f("fk_source_document_uploaded_by_app_user"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_document")),
        sa.UniqueConstraint(
            "tenant_id", "sha256", name=op.f("uq_source_document_tenant_id_sha256")
        ),
    )
    op.create_index(
        op.f("ix_source_document_tenant_id"), "source_document", ["tenant_id"], unique=False
    )
    op.create_table(
        "run",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=True),
        sa.Column("progress", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error", sa.Text(), nullable=False),
        sa.Column("started_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source_document.id"],
            name=op.f("fk_run_source_id_source_document"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["started_by"],
            ["app_user.id"],
            name=op.f("fk_run_started_by_app_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenant.id"], name=op.f("fk_run_tenant_id_tenant"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run")),
    )
    op.create_index(op.f("ix_run_source_id"), "run", ["source_id"], unique=False)
    op.create_index(op.f("ix_run_status"), "run", ["status"], unique=False)
    op.create_index(op.f("ix_run_tenant_id"), "run", ["tenant_id"], unique=False)
    op.create_table(
        "source_clause",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("number", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("kind", sa.String(length=8), nullable=False),
        sa.Column("normative", sa.Boolean(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("parent_number", sa.String(length=32), nullable=True),
        sa.Column("page_start", sa.Integer(), nullable=False),
        sa.Column("page_end", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("has_obligation", sa.Boolean(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source_document.id"],
            name=op.f("fk_source_clause_source_id_source_document"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_source_clause_tenant_id_tenant"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_clause")),
        sa.UniqueConstraint("source_id", "number", name=op.f("uq_source_clause_source_id_number")),
    )
    op.create_index(
        op.f("ix_source_clause_source_id"), "source_clause", ["source_id"], unique=False
    )
    op.create_index(
        op.f("ix_source_clause_tenant_id"), "source_clause", ["tenant_id"], unique=False
    )
    op.create_table(
        "source_page",
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("page_no", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source_document.id"],
            name=op.f("fk_source_page_source_id_source_document"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_source_page_tenant_id_tenant"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("source_id", "page_no", name=op.f("pk_source_page")),
    )
    op.create_index(op.f("ix_source_page_tenant_id"), "source_page", ["tenant_id"], unique=False)
    op.create_table(
        "requirement",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("clause_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=48), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("obligation", sa.String(length=8), nullable=False),
        sa.Column("category", sa.String(length=16), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("quote", sa.Text(), nullable=False),
        sa.Column("quote_verified", sa.Boolean(), nullable=False),
        sa.Column("page_no", sa.Integer(), nullable=True),
        sa.Column("applicability", sa.String(length=200), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("generated_by", sa.String(length=64), nullable=True),
        sa.Column("edited_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["clause_id"],
            ["source_clause.id"],
            name=op.f("fk_requirement_clause_id_source_clause"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["edited_by"],
            ["app_user.id"],
            name=op.f("fk_requirement_edited_by_app_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source_document.id"],
            name=op.f("fk_requirement_source_id_source_document"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_requirement_tenant_id_tenant"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_requirement")),
        sa.UniqueConstraint("source_id", "code", name=op.f("uq_requirement_source_id_code")),
    )
    op.create_index(op.f("ix_requirement_clause_id"), "requirement", ["clause_id"], unique=False)
    op.create_index(op.f("ix_requirement_source_id"), "requirement", ["source_id"], unique=False)
    op.create_index(op.f("ix_requirement_tenant_id"), "requirement", ["tenant_id"], unique=False)
    op.create_table(
        "run_event",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column(
            "at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("level", sa.String(length=8), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"], ["run.id"], name=op.f("fk_run_event_run_id_run"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_run_event_tenant_id_tenant"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_event")),
    )
    op.create_index(op.f("ix_run_event_run_id"), "run_event", ["run_id"], unique=False)
    op.create_index(op.f("ix_run_event_tenant_id"), "run_event", ["tenant_id"], unique=False)
    # ### end Alembic commands ###

    for table in TENANT_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation ON {table}
              USING (tenant_id = app_current_tenant())
              WITH CHECK (tenant_id = app_current_tenant());
            """
        )
    # 작업 기록은 추가만 한다.
    op.execute(f"REVOKE UPDATE, DELETE, TRUNCATE ON run_event FROM {APP_ROLE}")

    # 작업자는 어느 회사의 작업이 대기 중인지 미리 알 수 없다(행 수준 보안 때문에 보이지 않는다).
    # 그래서 '다음 작업 하나를 집어 실행 중으로 바꾸고 회사와 함께 돌려주는' 일만
    # 소유자 권한으로 한다.
    # 그 뒤의 모든 처리는 그 회사 범위 안에서 애플리케이션 역할로 한다.
    op.execute(
        """
        CREATE FUNCTION claim_next_run() RETURNS TABLE (run_id uuid, run_tenant uuid)
        LANGUAGE plpgsql
        SECURITY DEFINER
        SET search_path = public, pg_temp
        AS $$
        BEGIN
          RETURN QUERY
          UPDATE run r SET status = 'running', started_at = now()
          WHERE r.id = (
            SELECT q.id FROM run q WHERE q.status = 'queued'
            ORDER BY q.created_at FOR UPDATE SKIP LOCKED LIMIT 1
          )
          RETURNING r.id, r.tenant_id;
        END $$;
        """
    )
    # 서버가 꺼지면서 '실행 중' 으로 남은 작업을 실패로 정리한다. 작업자가 시작할 때 부른다.
    op.execute(
        """
        CREATE FUNCTION fail_interrupted_runs() RETURNS integer
        LANGUAGE plpgsql
        SECURITY DEFINER
        SET search_path = public, pg_temp
        AS $$
        DECLARE n integer;
        BEGIN
          UPDATE run SET status = 'failed', finished_at = now(),
                         error = '서버가 다시 시작되어 작업이 중단됐습니다. 다시 실행하세요.'
          WHERE status = 'running';
          GET DIAGNOSTICS n = ROW_COUNT;
          UPDATE source_document SET status = 'extracted' WHERE status = 'mining';
          RETURN n;
        END $$;
        """
    )
    for function in ("claim_next_run()", "fail_interrupted_runs()"):
        op.execute(f"REVOKE ALL ON FUNCTION {function} FROM PUBLIC")
        op.execute(f"GRANT EXECUTE ON FUNCTION {function} TO {APP_ROLE}")


def downgrade() -> None:
    op.execute("DROP FUNCTION IF EXISTS fail_interrupted_runs()")
    op.execute("DROP FUNCTION IF EXISTS claim_next_run()")
    for table in TENANT_TABLES:
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_run_event_tenant_id"), table_name="run_event")
    op.drop_index(op.f("ix_run_event_run_id"), table_name="run_event")
    op.drop_table("run_event")
    op.drop_index(op.f("ix_requirement_tenant_id"), table_name="requirement")
    op.drop_index(op.f("ix_requirement_source_id"), table_name="requirement")
    op.drop_index(op.f("ix_requirement_clause_id"), table_name="requirement")
    op.drop_table("requirement")
    op.drop_index(op.f("ix_source_page_tenant_id"), table_name="source_page")
    op.drop_table("source_page")
    op.drop_index(op.f("ix_source_clause_tenant_id"), table_name="source_clause")
    op.drop_index(op.f("ix_source_clause_source_id"), table_name="source_clause")
    op.drop_table("source_clause")
    op.drop_index(op.f("ix_run_tenant_id"), table_name="run")
    op.drop_index(op.f("ix_run_status"), table_name="run")
    op.drop_index(op.f("ix_run_source_id"), table_name="run")
    op.drop_table("run")
    op.drop_index(op.f("ix_source_document_tenant_id"), table_name="source_document")
    op.drop_table("source_document")
    # ### end Alembic commands ###
