"""basis plans coverage

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-06 22:37:01.821803
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0005"
down_revision = "0004"
branch_labels = None
depends_on = None

TENANT_TABLES = ["system_basis", "requirement_exclusion", "generation_plan", "document_requirement"]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "generation_plan",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("system_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("scope_code", sa.String(length=8), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("structure", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("uncovered", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("results", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("accepted_by", sa.UUID(), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["accepted_by"],
            ["app_user.id"],
            name=op.f("fk_generation_plan_accepted_by_app_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["app_user.id"],
            name=op.f("fk_generation_plan_created_by_app_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source_document.id"],
            name=op.f("fk_generation_plan_source_id_source_document"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["system_id"],
            ["process_system.id"],
            name=op.f("fk_generation_plan_system_id_process_system"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_generation_plan_tenant_id_tenant"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_generation_plan")),
    )
    op.create_index(
        op.f("ix_generation_plan_system_id"), "generation_plan", ["system_id"], unique=False
    )
    op.create_index(
        op.f("ix_generation_plan_tenant_id"), "generation_plan", ["tenant_id"], unique=False
    )
    op.create_table(
        "system_basis",
        sa.Column("system_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("approved_by", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["app_user.id"],
            name=op.f("fk_system_basis_approved_by_app_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["app_user.id"],
            name=op.f("fk_system_basis_created_by_app_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source_document.id"],
            name=op.f("fk_system_basis_source_id_source_document"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["system_id"],
            ["process_system.id"],
            name=op.f("fk_system_basis_system_id_process_system"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_system_basis_tenant_id_tenant"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("system_id", "source_id", name=op.f("pk_system_basis")),
    )
    op.create_index(op.f("ix_system_basis_tenant_id"), "system_basis", ["tenant_id"], unique=False)
    op.create_table(
        "requirement_exclusion",
        sa.Column("system_id", sa.UUID(), nullable=False),
        sa.Column("requirement_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("excluded_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["excluded_by"],
            ["app_user.id"],
            name=op.f("fk_requirement_exclusion_excluded_by_app_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["requirement_id"],
            ["requirement.id"],
            name=op.f("fk_requirement_exclusion_requirement_id_requirement"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["system_id"],
            ["process_system.id"],
            name=op.f("fk_requirement_exclusion_system_id_process_system"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_requirement_exclusion_tenant_id_tenant"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "system_id", "requirement_id", name=op.f("pk_requirement_exclusion")
        ),
    )
    op.create_index(
        op.f("ix_requirement_exclusion_tenant_id"),
        "requirement_exclusion",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "document_requirement",
        sa.Column("revision_id", sa.UUID(), nullable=False),
        sa.Column("section_key", sa.String(length=32), nullable=False),
        sa.Column("requirement_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.id"],
            name=op.f("fk_document_requirement_document_id_document"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["requirement_id"],
            ["requirement.id"],
            name=op.f("fk_document_requirement_requirement_id_requirement"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["revision_id"],
            ["document_revision.id"],
            name=op.f("fk_document_requirement_revision_id_document_revision"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_document_requirement_tenant_id_tenant"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "revision_id", "section_key", "requirement_id", name=op.f("pk_document_requirement")
        ),
    )
    op.create_index(
        op.f("ix_document_requirement_document_id"),
        "document_requirement",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_requirement_tenant_id"),
        "document_requirement",
        ["tenant_id"],
        unique=False,
    )
    op.add_column("run", sa.Column("plan_id", sa.UUID(), nullable=True))
    op.create_index(op.f("ix_run_plan_id"), "run", ["plan_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_run_plan_id_generation_plan"),
        "run",
        "generation_plan",
        ["plan_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###

    for table in TENANT_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation ON {table}
              USING (tenant_id = app_current_tenant())
              WITH CHECK (tenant_id = app_current_tenant());
            """
        )

    # 서버가 꺼지면서 중단된 작업을 정리할 때, 그 작업이 다루던 설계안도 '진행 중' 으로 남지
    # 않게 한다. 아직 시작하지 않은(대기 중인) 작업의 설계안은 건드리지 않는다.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION fail_interrupted_runs() RETURNS integer
        LANGUAGE plpgsql
        SECURITY DEFINER
        SET search_path = public, pg_temp
        AS $$
        DECLARE n integer;
        BEGIN
          UPDATE run SET status = 'failed', finished_at = now(),
                         error = '서버가 다시 시작되어 작업이 중단됐습니다. 다시 실행하세요.'
          WHERE status = 'running';
          GET DIAGNOSTICS n = ROW_COUNT;
          UPDATE source_document SET status = 'extracted' WHERE status = 'mining';
          UPDATE generation_plan p
          SET status = CASE p.status WHEN 'designing' THEN 'failed' ELSE 'partial' END
          WHERE p.status IN ('designing', 'writing')
            AND NOT EXISTS (
              SELECT 1 FROM run r WHERE r.plan_id = p.id AND r.status = 'queued'
            );
          RETURN n;
        END $$;
        """
    )


def downgrade() -> None:
    for table in TENANT_TABLES:
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_run_plan_id_generation_plan"), "run", type_="foreignkey")
    op.drop_index(op.f("ix_run_plan_id"), table_name="run")
    op.drop_column("run", "plan_id")
    op.drop_index(op.f("ix_document_requirement_tenant_id"), table_name="document_requirement")
    op.drop_index(op.f("ix_document_requirement_document_id"), table_name="document_requirement")
    op.drop_table("document_requirement")
    op.drop_index(op.f("ix_requirement_exclusion_tenant_id"), table_name="requirement_exclusion")
    op.drop_table("requirement_exclusion")
    op.drop_index(op.f("ix_system_basis_tenant_id"), table_name="system_basis")
    op.drop_table("system_basis")
    op.drop_index(op.f("ix_generation_plan_tenant_id"), table_name="generation_plan")
    op.drop_index(op.f("ix_generation_plan_system_id"), table_name="generation_plan")
    op.drop_table("generation_plan")
    # ### end Alembic commands ###
